-- Insert documents into the docs table
INSERT INTO public.docs (id, title, authors, publication_date, abstract, keywords)
VALUES 
(1, 'BIG DATA ANALYTICS', '{"Philip Russom"}', '2023-01-01', 'This document explores the concepts and applications of Big Data Analytics...', '{"Big Data", "Analytics"}'),
(2, 'Big Data Deep Learning Challenges and perspective', '{"XUE-WEN CHEN", "XIAOTONG LIN"}', '2022-12-15', 'This paper discusses the challenges and perspectives of implementing Deep Learning techniques in Big Data environments...', '{"Deep Learning", "Challenges", "Perspective"}'),
(3, 'Big Data', '{"Seref SAGIROGLU", "Duygu SINANC"}', '2023-02-01', 'This document provides an overview of Big Data technologies, applications, and challenges...', '{"Big Data", "Technologies", "Applications"}'),
(4, 'Data Mining with Big Data', '{"Xindong Wu", "Xingquan Zhu", "Gong-Qing Wu", "Wei Ding"}', '2023-03-10', 'This paper focuses on data mining techniques, algorithms, and applications in Big Data environments...', '{"Data Mining", "Big Data", "Techniques"}'),
(5, 'Machine learning and deep learning', '{"Christian Janiesch", "Patrick Zschech", "Kai Heinrich"}', '2022-11-20', 'This document explores machine learning and deep learning concepts, algorithms, and applications...', '{"Machine Learning", "Deep Learning", "Algorithms"}'),
(6, 'Machine learning', '{"M. I. Jordan", "T. M. Mitchell"}', '2022-10-05', 'This paper focuses on machine learning algorithms, methodologies, and applications...', '{"Machine Learning", "Algorithms", "Applications"}'),
(7, 'Recent advances in deep learning', '{"Xizhao Wang", "Yanxia Zhao", "Farhad Pourpanah"}', '2022-09-15', 'This paper discusses recent advances, trends, and innovations in deep learning research and applications...', '{"Deep Learning", "Advances", "Trends"}'),
(8, 'Data Analytics', '{"Thomas A. Runkler"}', '2023-04-05', 'This document provides insights into data analytics techniques, tools, and applications...', '{"Data Analytics", "Techniques", "Tools"}');